name: 'Pull Request Labeler'
description: 'Automatically labels pull requests based on criteria'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq  # Update for different OS
      shell: bash
      
    - uses: actions/checkout@v2

    - name: Analyze Pull Request
      run: |
        PR_TITLE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.title')
        PR_BODY=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')

        if [[ "$PR_TITLE" == *"bug"* || "$PR_BODY" == *"fix"* ]]; then
          echo "Found bug-related content. Adding 'bug' label."
          LABEL_TO_ADD="bug"
        elif [[ "$PR_TITLE" == *"feature"* || "$PR_BODY" == *"feature"* ]]; then
          echo "Found feature-related content. Adding 'feature' label."
          LABEL_TO_ADD="feature"
        else
          echo "No specific criteria met for labeling."
          LABEL_TO_ADD=""
        fi

        if [[ -n "$LABEL_TO_ADD" ]]; then
          curl -X POST -H "Authorization: token ${{ inputs.github-token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
            -d "{\"labels\":[\"$LABEL_TO_ADD\"]}"
        fi
      shell: bash
