name: 'Pull Request Labeler'
description: 'Automatically labels pull requests based on criteria'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
outputs:
  PR_NUMBER:
    description: "PR number"
    value: ${{ steps.analyze-pr.outputs.PR_NUMBER}}
  PR_TITLE:
    description: "PR title"
    value: ${{ steps.analyze-pr.outputs.PR_TITLE}}
  PR_BODY:
    description: "PR body"
    value: ${{ steps.analyze-pr.outputs.PR_BODY}}
runs:
  using: 'composite'
  steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq  # Update for different OS
      shell: bash
      
    - uses: actions/checkout@v2

    - name: Analyze Pull Request
      id: analyze-pr
      run: |
        # Display PR number
        echo "Pull Request Number: ${{ github.event.pull_request.number }}"

        # Display GitHub Token (for debugging purposes only)
        echo "GitHub Token: ${{ inputs.github-token }}"

        PR_DATA=$(curl -s -H "Authorization: token ${{ inputs.github-token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")

        PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
        PR_BODY=$(echo "$PR_DATA" | jq -r '.body')
        
        echo "Debug Information:"
        echo "PR_TITLE= $PR_TITLE"
        echo "PR_BODY= $PR_BODY"

        if [[ "$PR_TITLE" == *"bug"* || "$PR_BODY" == *"fix"* ]]; then
          echo "Found bug-related content. Adding 'bug' label."
          LABEL_TO_ADD="bug"
        elif [[ "$PR_TITLE" == *"feature"* || "$PR_BODY" == *"feature"* ]]; then
          echo "Found feature-related content. Adding 'feature' label."
          LABEL_TO_ADD="feature"
        else
          echo "No specific criteria met for labeling."
          LABEL_TO_ADD=""
        fi

        if [[ -n "$LABEL_TO_ADD" ]]; then
          curl -X POST -H "Authorization: token ${{ inputs.github-token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
            -d "{\"labels\":[\"$LABEL_TO_ADD\"]}"
        fi
      shell: bash
