name: Test Pull Request Trigger

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test My Action
        uses: ./  # Use the relative path to the directory containing your action.yml
        with:
          github-token: ${{ secrets.GH_TOKEN }}  # Replace with your specific input variables
          
